### ISSUE TITLE
[Bug] 尝试绑定maimai账号时出现错误

### ISSUE THREAD

**Issue by shinyashen** [Dreamail/maimai-prober-qbot-updater#1]
![image](https://github.com/Dreamail/maimai-prober-qbot-updater/assets/90324553/225c44d0-24d5-4a8e-92ff-293c541cf966)
系统：Windows 11 专业工作站版 x64
使用最新构建中的[windows_amd64](https://github.com/Dreamail/maimai-prober-qbot-updater/suites/14462553276/artifacts/816833609)文件进行操作

**Comment by Dreamail** [comment]
好友代码绑定是`mai bindmai`指令而不是`mai bindmaimai`
多出来的一个mai会被当作指令参数传递
（上游ZeroBot的特性

**Comment by Dreamail** [comment]
（我哭死，居然有人给我的屎坑开issue
BTW，现在项目正在用Python重写以移植至nonebot2框架，现有golang版本可能不会得到更新，但issue有时间还是会处理的
（主要是高三忙了好多
但其实现有版本也算稳定了的

**Comment by Dreamail** [comment]
没有回复我就close了

**Comment by shinyashen** [comment]
（我的qq邮箱推送把所有的github订阅全设置成垃圾邮件了。。。
确实是我没有看清楚文档，我的锅qaq
希望高三顺利！
